-- #SCOOTER

UPDATE SCOOTER SET CAPACIDADE_ATUAL = 60.0 WHERE MATRICULA LIKE '53-LL-93';
UPDATE SCOOTER SET CAPACIDADE_ATUAL = 25.0 WHERE MATRICULA LIKE '17-XD-38';
UPDATE SCOOTER SET CAPACIDADE_ATUAL = 33.0 WHERE MATRICULA LIKE '38-LB-13';